TDW\UserApi\Entity\Group:
    type: entity
    # repositoryClass: TDW\UserApi\Entity\GroupRepository
    table: groups
    uniqueConstraints:
        groupname_UNIQUE:
            columns:
                - groupname
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: 'Resource identifier. This property is read-only.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        groupname:
            type: string
            nullable: false
            length: 32
            fixed: false
        description:
            type: string
            nullable: true
            length: 126
            fixed: false
            comment: 'Group Description.'
    lifecycleCallbacks: {  }
